version: '3.9'
services:
    db:
        image: postgres:alpine
        ports:
            - '${DATABASE_PORT}:5432'
        volumes:
            - ./src/database:/var/lib/postgresql
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
