version: '3.9'
services:
    back-end:
        image: nlw-valoriza/back-end:1.0.0
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - .:/usr/src/app
        restart: always
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
            target: ${NODE_ENV}
            args:
                port: ${PORT}
        depends_on:
            - ${DATABASE_LINK}
    db:
        image: postgres:alpine
        ports:
            - '${DATABASE_HOST_PORT}:5432'
        volumes:
            - /var/lib/nlw-valoriza-db:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
